[package]
name = "io"
version = "0.1.5"
authors = ["KizzyCode <development@kizzycode.de>"]
build = "build.rs"

[dependencies]
etrace = { git = "https://github.com/KizzyCode/etrace" }
future = { git = "https://github.com/KizzyCode/future" }